name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        nim-version: ['1.2.16', '1.4.0', '1.6.0', '1.6.x', '2.0.0', 'stable', 'devel']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache choosenim
      if: ${{ matrix.nim-version != 'devel' }}
      uses: actions/cache@v4
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}
        restore-keys: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}

    - name: Get date
      if: ${{ matrix.nim-version == 'devel' }}
      id: get-date
      run: echo "date=$(date "+%Y-%m-%d")" > $GITHUB_OUTPUT
      shell: bash

    - name: Cache choosenim devel
      if: ${{ matrix.nim-version == 'devel' }}
      uses: actions/cache@v4
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}-${{ steps.get-date.outputs.date }}
        restore-keys: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}-

    - name: Cache nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        restore-keys: ${{ runner.os }}-nimble-

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests with balls
      if: ${{ matrix.os == 'ubuntu-latest' && (matrix.nim-version == 'stable' || matrix.nim-version == 'devel') }}
      run: |
        nimble install -y https://github.com/disruptek/balls jsony
        balls -b:c -d:debug -d:release -d:danger --mm:arc --mm:orc -d:staticSqlite

    - name: Run tests with balls@v3
      if: ${{ matrix.nim-version == '1.6.x' || matrix.nim-version == '2.0.0' || matrix.os != 'ubuntu-latest' && (matrix.nim-version == 'stable' || matrix.nim-version == 'devel') }}
      run: |
        nimble install -y https://github.com/disruptek/balls@#v3 jsony
        balls -b:c -d:debug -d:release -d:danger --mm:arc --mm:orc -d:staticSqlite

    - name: Run tests with nimble test
      if: ${{ matrix.nim-version == '1.2.16' || matrix.nim-version == '1.4.0' || matrix.nim-version == '1.6.0' }}
      run: |
        nimble test -y --gc:arc -d:staticSqlite
        nimble test -y --gc:orc -d:staticSqlite
        nimble test -y -d:release --gc:arc -d:staticSqlite
        nimble test -y -d:release --gc:orc -d:staticSqlite
        nimble test -y -d:danger --gc:arc -d:staticSqlite
        nimble test -y -d:danger --gc:orc -d:staticSqlite
