name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        nim-version: ['1.4.x', '1.6.0', '1.6.x', '2.0.0', 'stable', 'devel']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests with balls
      if: ${{ matrix.os == 'ubuntu-latest' && (matrix.nim-version == 'stable' || matrix.nim-version == 'devel') }}
      run: |
        nimble install -y https://github.com/disruptek/balls
        balls -b:c -d:debug -d:release -d:danger --mm:arc --mm:orc -d:staticSqlite

    - name: Run tests with balls@v3
      if: ${{ !(matrix.os == 'ubuntu-latest' && (matrix.nim-version == 'stable' || matrix.nim-version == 'devel')) && matrix.nim-version != '1.6.0' && matrix.nim-version != '1.4.x' }}
      run: |
        nimble install -y https://github.com/disruptek/balls@#v3
        balls -b:c -d:debug -d:release -d:danger --mm:arc --mm:orc -d:staticSqlite

    - name: Run tests with nimble test
      if: ${{ matrix.nim-version == '1.6.0' || matrix.nim-version == '1.4.x' }}
      run: |
        nimble test -y --gc:arc -d:staticSqlite
        nimble test -y --gc:orc -d:staticSqlite
        nimble test -y -d:release --gc:arc -d:staticSqlite
        nimble test -y -d:release --gc:orc -d:staticSqlite
        nimble test -y -d:danger --gc:arc -d:staticSqlite
        nimble test -y -d:danger --gc:orc -d:staticSqlite
